logging:
  level:
    root: info
    com.fish1208.config: debug
    com.fish1208.sdk: debug
    com.fish1208.controller: debug
    com.fish1208.common: debug
    
fabric-config:
  league:
    name: fish1208
  channel:
    name: mychannel
    block-listener: true

  orderers:
    - name: orderer.example.com
      location: 192.168.229.167:7050
      domain-name: example.com
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.key
    - name: orderer2.example.com
      location: 192.168.229.167:8050
      domain-name: example.com
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.key
    - name: orderer3.example.com
      location: 192.168.229.167:9050
      domain-name: example.com
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.key
    - name: orderer4.example.com
      location: 192.168.229.167:10050
      domain-name: example.com
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/orderers/orderer4.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.key
    - name: orderer5.example.com
      location: 192.168.229.167:11050
      domain-name: example.com
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/orderers/orderer5.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/client.key

  chaincodes:
    - name: mycc
      source: opt/gopath
      path: github.com/hyperledger/fabric/peer/chaincode/go/chaincode_example02/
      version: 1.0
      proposal-waittime: 60000
      event-listener: true
      callback-location:
      events: saveEvent
    - name: personcc
      source: opt/gopath
      path: github.com/hyperledger/fabric/peer/chaincode/go/person_cc/
      version: 1.0
      proposal-waittime: 60000
      event-listener: true
      callback-location:
      events: saveEvent

  org1:
    id: 1
    tls: true
    msp-id: Org1MSP
    domain-name: org1.example.com

  peers1:
    - name: peer0.org1.example.com
      location: 192.168.229.167:7051
      eventhub-location:
      org-id: 1
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key
    - name: peer1.org1.example.com
      location: 192.168.229.167:8051
      eventhub-location:
      org-id: 1
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/users/User1@org1.example.com/tls/client.key

  org2:
    id: 2
    tls: true
    msp-id: Org2MSP
    domain-name: org2.example.com

  peers2:
    - name: peer0.org2.example.com
      location: 192.168.229.167:9051
      eventhub-location:
      org-id: 2
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/tls/client.key
    - name: peer1.org2.example.com
      location: 192.168.229.167:10051
      eventhub-location:
      org-id: 2
      server-crt-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls/server.crt
      client-cert-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/tls/client.crt
      client-key-path: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/users/User1@org2.example.com/tls/client.key

  ca1:
    name: ca1
    sk: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/d82e8988b27155f43d89fa63f95aff71262fda48748baa4a80bc649dd4450793_sk
    certificate: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem

  ca2:
    name: ca2
    sk: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/2c00551a305fad774acc272ed559e8ca991de904b34b8ddca51006563733fbc1_sk
    certificate: classpath:fabric-${spring.profiles.active}/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
